version: '3.1'

volumes:
  mongodb:

networks:
  go-api-net:

services:

  api:
    container_name: irannicholas-goapi
    build:
      context: .
    ports:
      - "9080:9080"
    depends_on:
      - db
    networks:
      - go-api-net

  db:
    container_name: irannicholas-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
     - mongodb:/data/db
    networks:
     - go-api-net